options:
  interface:
    type: string
    default: ""
    description: "Interface to set MAC address on (ex: eth0)"
  address:
    type: string
    default: ""
    description: "The MAC address to set (ex: XX:XX:XX:XX)"
